# Generated by Django 5.2.6 on 2025-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', '아파트'), ('OFFICETEL', '오피스텔'), ('ONE_ROOM', '원룸'), ('TWO_ROOM', '투룸'), ('VILLA', '빌라/주택')], default='APARTMENT', max_length=10),
        ),
    ]
